apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-canary-app-stable
  labels:
    app: ci-cd-canary-app
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-cd-canary-app
      track: stable
  template:
    metadata:
      labels:
        app: ci-cd-canary-app
        track: stable
    spec:
      containers:
        - name: app
          image: 447407244516.dkr.ecr.ap-south-1.amazonaws.com/ci-cd-canary-app:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
